version: '3.9'

services:
  #spring-boot:
   # build: .
    #container_name: spring
    #restart: unless-stopped
    #ports:
     # - "8080:8080"
   # depends_on:
   #   - db
   #   - minio
   # environment:
   #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
   #   SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
   #   SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
   #   MINIO_URL: http://minio:9000
   #   MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
   #   MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
  #    MINIO_BUCKET: recipes

  db:
    image: postgres:17.9
    container_name: recipe_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: recipe_minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: